language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.6"
      env: USE_PSALM=0
    - php: "7.0"
      env: USE_PSALM=0
    - php: "7.1"
      env: USE_PSALM=1
    - php: "7.2"
      env: USE_PSALM=1
    - php: "7.3"
      env: USE_PSALM=1
    - php: "nightly"
      env: USE_PSALM=1
    - php: "hhvm"
      env: USE_PSALM=1
  allow_failures:
    - php: "5.4"
    - php: "5.5"
    - php: "nightly"
    - php: "hhvm"